name: Deploy to GKE Autopilot

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate with GCP
        run: |
          echo '${{ secrets.GCP_SA_KEY }}' > gcp-key.json
          gcloud auth activate-service-account --key-file=gcp-key.json
          gcloud auth list
        env:
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: upgradlabs-1738334790345

      - name: Configure Docker authentication
        run: |
          gcloud auth configure-docker us-central1-docker.pkg.dev --quiet

      - name: Build and Push Docker Image
        run: |
          IMAGE_NAME=us-central1-docker.pkg.dev/upgradlabs-1738334790345/amit23comp/gke-webpage
          TAG=$(echo $GITHUB_SHA | cut -c1-7)  # Short Git SHA for versioning
          docker build -t $IMAGE_NAME:$TAG .
          docker push $IMAGE_NAME:$TAG
          docker tag $IMAGE_NAME:$TAG $IMAGE_NAME:latest
          docker push $IMAGE_NAME:latest

      - name: Get GKE Credentials
        run: |
          gcloud container clusters get-credentials autopilot-cluster-1 \
            --region us-central1 \
            --project upgradlabs-1738334790345

      - name: Deploy to GKE
        run: |
          kubectl apply -f k8s/deployment.yaml
          kubectl apply -f k8s/service.yaml
          kubectl rollout status deployment/gke-webpage -n default  # Wait for deployment

      - name: Verify Deployment
        run: kubectl get services -o wide
