- name: Authenticate with GCP
  run: |
    echo "$GCP_SA_KEY" | base64 --decode > gcp-key.json
    gcloud auth activate-service-account --key-file=gcp-key.json
  env:
    GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
